from __future__ import annotations

"""
Renko chart selection strategy v5.

Market-regime adaptive version based on v4.

Important current rule:
- Market-regime is temporarily NOT part of the common indicator cache.
- v5 still reads SH#999999.txt directly and merges market_regime by date.
- Other stock-level indicator facts are generated by indicators/ and checked here.
"""

from functools import lru_cache
from pathlib import Path

from config import RAW_TDX_TXT_DIR
from typing import Optional

import pandas as pd

from indicators import add_all_indicators
from indicators.required import require_indicator_columns


STRATEGY_NAME = "renko_chart_select_strategy_v5"

REQUIRED_STOCK_INDICATORS: set[str] = {
    "date", "open", "high", "low", "close", "volume",
    "brick_value", "brick_prev_1", "brick_prev_2",
    "current_red_height", "previous_green_height",
    "daily_return_pct", "short_trend",
    "hard_brick_turn_strong",
    "price_rise_range_and_close_to_short_trend_below_limit",
    "strong_price_rise_range_and_close_to_short_trend_below_limit",
    "close_to_short_trend",
    "close_to_short_trend_below_084",
    "close_to_short_trend_below_086",
    "close_to_short_trend_below_088",
    "close_to_short_trend_below_090",
    "daily_return_5_to_7",
    "daily_return_55_to_7",
    "daily_return_6_to_7",
    "brick_reversal_ratio",
    "brick_reversal_strength_100",
    "brick_reversal_strength_120",
    "brick_reversal_strength_below_100",
    "brick_reversal_strength_below_090",
}

REQUIRED_MARKET_COLUMNS: set[str] = {
    "market_regime", "strong_market", "normal_market", "weak_market",
}

REQUIRED_INDICATORS = REQUIRED_STOCK_INDICATORS | REQUIRED_MARKET_COLUMNS
REQUIRED_INDICATOR_COLUMNS = REQUIRED_STOCK_INDICATORS

DEFAULT_MARKET_INDEX_PATH = RAW_TDX_TXT_DIR / "SH#999999.txt"

DEFAULT_MIN_DAILY_RETURN_PCT = 3.0
DEFAULT_MAX_DAILY_RETURN_PCT = 7.0
DEFAULT_MAX_CLOSE_TO_SHORT_TREND = 0.95
STRONG_MAX_DAILY_RETURN_PCT = 9.0
STRONG_MAX_CLOSE_TO_SHORT_TREND = 1.00

SCORE_WEIGHTS = {
    "close_to_short_trend_below_090": 30.0,
    "close_to_short_trend_below_088": 20.0,
    "close_to_short_trend_below_086": 12.0,
    "close_to_short_trend_below_084": 8.0,
    "daily_return_5_to_7": 10.0,
    "daily_return_55_to_7": 6.0,
    "daily_return_6_to_7": 4.0,
    "brick_reversal_strength_below_100": 4.0,
    "brick_reversal_strength_below_090": 3.0,
    "brick_reversal_strength_100": -22.0,
    "brick_reversal_strength_120": -10.0,
}

POSITIVE_MAX_SCORE = sum(v for v in SCORE_WEIGHTS.values() if v > 0)


# =============================================================================
# Market index parser
# =============================================================================

def parse_tdx_date(date_raw: str) -> pd.Timestamp:
    """
    Safely parse TongDaXin date.

    Supports:
    - 2026-05-06
    - 2026/05/06
    - 20260506
    - 06/05/2026  -> treated as day/month/year
    - 06-05-2026  -> treated as day/month/year
    """

    s = str(date_raw).strip()

    if not s:
        return pd.NaT

    formats = [
        "%Y-%m-%d",
        "%Y/%m/%d",
        "%Y%m%d",
        "%d/%m/%Y",
        "%d-%m-%Y",
    ]

    for fmt in formats:
        dt = pd.to_datetime(s, format=fmt, errors="coerce")
        if pd.notna(dt):
            return dt

    return pd.to_datetime(s, errors="coerce", dayfirst=True)


def read_tdx_index_txt(path: Path) -> pd.DataFrame:
    """
    Read TongDaXin index txt.

    Expected columns:
        date open high low close volume amount

    Parser is tolerant for:
    - space separated
    - comma separated
    - tab separated
    - Chinese header lines
    """

    if not path.exists():
        raise FileNotFoundError(f"Market index txt file not found: {path}")

    encodings = ["gbk", "utf-8-sig", "utf-8"]
    lines = None
    last_error: Optional[Exception] = None

    for enc in encodings:
        try:
            with path.open("r", encoding=enc, errors="ignore") as f:
                lines = f.readlines()
            break
        except Exception as e:
            last_error = e

    if lines is None:
        raise RuntimeError(f"Failed to read market index file: {path}. Last error: {last_error}")

    rows: list[dict] = []

    for line in lines:
        raw = line.strip()

        if not raw:
            continue

        if any(x in raw for x in ["日期", "时间", "证券", "代码", "数据来源", "名称"]):
            continue

        normalized = (
            raw.replace(",", " ")
            .replace("\t", " ")
            .replace("，", " ")
        )

        parts = [p for p in normalized.split(" ") if p]

        if len(parts) < 5:
            continue

        date = parse_tdx_date(parts[0])

        if pd.isna(date):
            continue

        nums: list[Optional[float]] = []

        for p in parts[1:]:
            try:
                nums.append(float(p))
            except ValueError:
                nums.append(None)

        if len(nums) < 4:
            continue

        open_price = nums[0]
        high = nums[1]
        low = nums[2]
        close = nums[3]
        volume = nums[4] if len(nums) >= 5 else None
        amount = nums[5] if len(nums) >= 6 else None

        if open_price is None or high is None or low is None or close is None:
            continue

        rows.append(
            {
                "date": date,
                "index_open": open_price,
                "index_high": high,
                "index_low": low,
                "index_close": close,
                "index_volume": volume,
                "index_amount": amount,
            }
        )

    if not rows:
        raise ValueError(f"No valid market index rows parsed from: {path}")

    df = pd.DataFrame(rows)
    df = df.drop_duplicates(subset=["date"], keep="last")
    df = df.sort_values("date").reset_index(drop=True)

    today = pd.Timestamp.today().normalize()
    df = df[df["date"] <= today].reset_index(drop=True)

    return df


def add_market_regime_to_index(
    index_df: pd.DataFrame,
    *,
    ma_short: int = 20,
    ma_long: int = 50,
    ret_window: int = 5,
) -> pd.DataFrame:
    """
    Add market regime to index dataframe.

    strong:
        index_close > index_ma20
        AND index_ma20 > index_ma50

    weak:
        index_close < index_ma20
        AND index_ma20 < index_ma50

    normal:
        otherwise
    """

    out = index_df.copy()

    close = pd.to_numeric(out["index_close"], errors="coerce")

    ma_short_col = f"index_ma{ma_short}"
    ma_long_col = f"index_ma{ma_long}"
    ret_col = f"index_ret_{ret_window}d_pct"

    out[ma_short_col] = close.rolling(ma_short, min_periods=ma_short).mean()
    out[ma_long_col] = close.rolling(ma_long, min_periods=ma_long).mean()
    out[ret_col] = close / close.shift(ret_window) * 100.0 - 100.0

    out["index_above_ma_short"] = close > out[ma_short_col]
    out["index_below_ma_short"] = close < out[ma_short_col]

    out["index_ma_short_above_ma_long"] = out[ma_short_col] > out[ma_long_col]
    out["index_ma_short_below_ma_long"] = out[ma_short_col] < out[ma_long_col]

    out["strong_market"] = (
        out["index_above_ma_short"].fillna(False).astype(bool)
        & out["index_ma_short_above_ma_long"].fillna(False).astype(bool)
    )

    out["weak_market"] = (
        out["index_below_ma_short"].fillna(False).astype(bool)
        & out["index_ma_short_below_ma_long"].fillna(False).astype(bool)
    )

    out["normal_market"] = (
        ~out["strong_market"].fillna(False).astype(bool)
        & ~out["weak_market"].fillna(False).astype(bool)
    )

    out["market_regime"] = "normal"
    out.loc[out["strong_market"], "market_regime"] = "strong"
    out.loc[out["weak_market"], "market_regime"] = "weak"

    # Stable aliases.
    out["index_ma20"] = out[ma_short_col] if ma_short != 20 else out["index_ma20"]
    out["index_ma50"] = out[ma_long_col] if ma_long != 50 else out["index_ma50"]
    out["index_ret_5d_pct"] = out[ret_col] if ret_window != 5 else out["index_ret_5d_pct"]

    return out


@lru_cache(maxsize=8)
def load_market_regime_cached(
    market_index_path_str: str,
    ma_short: int = 20,
    ma_long: int = 50,
    ret_window: int = 5,
) -> pd.DataFrame:
    path = Path(market_index_path_str)

    index_df = read_tdx_index_txt(path)

    regime_df = add_market_regime_to_index(
        index_df,
        ma_short=ma_short,
        ma_long=ma_long,
        ret_window=ret_window,
    )

    keep_cols = [
        "date",
        "index_close",
        "index_ma20",
        "index_ma50",
        "index_ret_5d_pct",
        "strong_market",
        "normal_market",
        "weak_market",
        "market_regime",
    ]

    existing_cols = [c for c in keep_cols if c in regime_df.columns]

    return regime_df[existing_cols].copy()


def merge_market_regime(
    df: pd.DataFrame,
    *,
    market_index_path: Path = DEFAULT_MARKET_INDEX_PATH,
    market_ma_short: int = 20,
    market_ma_long: int = 50,
    market_ret_window: int = 5,
) -> pd.DataFrame:
    """
    Merge market regime into stock dataframe by date.

    If market data is missing for a row, fallback to normal.
    """

    out = df.copy()
    out["date"] = pd.to_datetime(out["date"], errors="coerce")

    regime_df = load_market_regime_cached(
        str(market_index_path),
        market_ma_short,
        market_ma_long,
        market_ret_window,
    )

    regime_df = regime_df.copy()
    regime_df["date"] = pd.to_datetime(regime_df["date"], errors="coerce")

    out = out.merge(regime_df, on="date", how="left")

    out["market_regime"] = out["market_regime"].fillna("normal")

    out["strong_market"] = out["strong_market"].fillna(False).astype(bool)
    out["weak_market"] = out["weak_market"].fillna(False).astype(bool)

    if "normal_market" in out.columns:
        out["normal_market"] = out["normal_market"].fillna(False).astype(bool)
    else:
        out["normal_market"] = (
            ~out["strong_market"].astype(bool)
            & ~out["weak_market"].astype(bool)
        )

    return out

# =============================================================================
# Strategy-only score / selection
# =============================================================================

def _prepare_indicators(df: pd.DataFrame, n1: int, n2: int, **kwargs) -> pd.DataFrame:
    if REQUIRED_STOCK_INDICATORS.issubset(set(df.columns)):
        out = df.copy().sort_values("date").reset_index(drop=True)
    else:
        out = add_all_indicators(df, n1=n1, n2=n2, **kwargs)
    require_indicator_columns(out, REQUIRED_STOCK_INDICATORS, STRATEGY_NAME)
    return out


def add_weighted_score(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    score_cols: list[str] = []
    for col, weight in SCORE_WEIGHTS.items():
        score_col = f"score_{col}" if weight > 0 else f"penalty_{col}"
        out[score_col] = out[col].fillna(False).astype(bool).astype(float) * weight
        score_cols.append(score_col)

    out["score"] = out[score_cols].sum(axis=1)
    out["score_pct"] = out["score"] / POSITIVE_MAX_SCORE * 100.0 if POSITIVE_MAX_SCORE > 0 else 0.0

    close_to_short_trend = pd.to_numeric(out["close_to_short_trend"], errors="coerce")
    daily_return_pct = pd.to_numeric(out["daily_return_pct"], errors="coerce")
    brick_reversal_ratio = pd.to_numeric(out["brick_reversal_ratio"], errors="coerce")

    out["rank_close_to_short_trend"] = close_to_short_trend.fillna(999.0)
    out["rank_daily_return_pct"] = daily_return_pct.fillna(-999.0)
    out["rank_brick_reversal_ratio"] = brick_reversal_ratio.fillna(999.0)

    out["score_rank_key"] = (
        out["score_pct"].fillna(0.0) * 100000.0
        + (1.0 - out["rank_close_to_short_trend"].clip(lower=0.0, upper=2.0)) * 10000.0
        + out["rank_daily_return_pct"].clip(lower=-20.0, upper=20.0) * 100.0
        + (1.0 - out["rank_brick_reversal_ratio"].clip(lower=0.0, upper=3.0)) * 1000.0
    )
    return out


def add_final_selection(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    require_indicator_columns(out, REQUIRED_INDICATORS, STRATEGY_NAME)

    is_strong = out["market_regime"].eq("strong")
    is_not_strong = ~is_strong

    out["selected_v4_base"] = (
        out["hard_brick_turn_strong"].fillna(False).astype(bool)
        & out["price_rise_range_and_close_to_short_trend_below_limit"].fillna(False).astype(bool)
    ).astype(int)

    out["selected_strong_relaxed"] = (
        out["hard_brick_turn_strong"].fillna(False).astype(bool)
        & out["strong_price_rise_range_and_close_to_short_trend_below_limit"].fillna(False).astype(bool)
    ).astype(int)

    out["selected_by_market_regime"] = 0
    out.loc[is_not_strong, "selected_by_market_regime"] = out.loc[is_not_strong, "selected_v4_base"]
    out.loc[is_strong, "selected_by_market_regime"] = out.loc[is_strong, "selected_strong_relaxed"]
    out["selected"] = out["selected_by_market_regime"].astype(int)
    return out


def select_renko_chart(
    df: pd.DataFrame,
    n1: int = 4,
    n2: int = 6,
    min_daily_return_pct: float = DEFAULT_MIN_DAILY_RETURN_PCT,
    max_daily_return_pct: float = DEFAULT_MAX_DAILY_RETURN_PCT,
    max_close_to_short_trend: float = DEFAULT_MAX_CLOSE_TO_SHORT_TREND,
    strong_max_daily_return_pct: float = STRONG_MAX_DAILY_RETURN_PCT,
    strong_max_close_to_short_trend: float = STRONG_MAX_CLOSE_TO_SHORT_TREND,
    market_index_path: Path = DEFAULT_MARKET_INDEX_PATH,
    market_ma_short: int = 20,
    market_ma_long: int = 50,
    market_ret_window: int = 5,
    **kwargs,
) -> pd.DataFrame:
    kwargs = dict(kwargs)
    kwargs.setdefault("min_daily_return_pct", min_daily_return_pct)
    kwargs.setdefault("max_daily_return_pct", max_daily_return_pct)
    kwargs.setdefault("max_close_to_short_trend", max_close_to_short_trend)
    kwargs.setdefault("strong_max_daily_return_pct", strong_max_daily_return_pct)
    kwargs.setdefault("strong_max_close_to_short_trend", strong_max_close_to_short_trend)

    out = _prepare_indicators(df, n1=n1, n2=n2, **kwargs)
    out = merge_market_regime(
        out,
        market_index_path=market_index_path,
        market_ma_short=market_ma_short,
        market_ma_long=market_ma_long,
        market_ret_window=market_ret_window,
    )
    out = add_weighted_score(out)
    out = add_final_selection(out)
    out["selection_strategy"] = STRATEGY_NAME
    return out


def select(
    df: pd.DataFrame,
    n1: int = 4,
    n2: int = 6,
    min_daily_return_pct: float = DEFAULT_MIN_DAILY_RETURN_PCT,
    max_daily_return_pct: float = DEFAULT_MAX_DAILY_RETURN_PCT,
    max_close_to_short_trend: float = DEFAULT_MAX_CLOSE_TO_SHORT_TREND,
    strong_max_daily_return_pct: float = STRONG_MAX_DAILY_RETURN_PCT,
    strong_max_close_to_short_trend: float = STRONG_MAX_CLOSE_TO_SHORT_TREND,
    market_index_path: Path = DEFAULT_MARKET_INDEX_PATH,
    market_ma_short: int = 20,
    market_ma_long: int = 50,
    market_ret_window: int = 5,
    **kwargs,
) -> pd.DataFrame:
    return select_renko_chart(
        df=df,
        n1=n1,
        n2=n2,
        min_daily_return_pct=min_daily_return_pct,
        max_daily_return_pct=max_daily_return_pct,
        max_close_to_short_trend=max_close_to_short_trend,
        strong_max_daily_return_pct=strong_max_daily_return_pct,
        strong_max_close_to_short_trend=strong_max_close_to_short_trend,
        market_index_path=market_index_path,
        market_ma_short=market_ma_short,
        market_ma_long=market_ma_long,
        market_ret_window=market_ret_window,
        **kwargs,
    )


def apply_strategy(df: pd.DataFrame, n1: int = 4, n2: int = 6, **kwargs) -> pd.DataFrame:
    return select(df=df, n1=n1, n2=n2, **kwargs)


def run(df: pd.DataFrame, n1: int = 4, n2: int = 6, **kwargs) -> pd.DataFrame:
    return select(df=df, n1=n1, n2=n2, **kwargs)


SELECT_FUNC = select
