from __future__ import annotations

"""
Renko chart selection strategy v3.

Changes from renko_chart_select_strategy_v2:

1. Strategy name is updated.
   - v2 name: renko_chart_select_strategy_v2
   - v3 name: renko_chart_select_strategy_v3

2. J-value hard condition is changed.
   - v2 hard condition: j_momentum_or_low must be true.
   - v3 hard condition: j_v3_range must be true.
   - j_v3_range definition:
     J < 0 OR 30 <= J < 50.
   - This keeps extreme-low reversal and mid-range recovery signals.

3. close_below_short_trend_cap is reversed for scoring.
   - v2: close_below_short_trend_cap=True received positive score.
   - v3: close_above_short_trend_cap=True receives positive score.
   - close_above_short_trend_cap is defined as:
     close_below_short_trend_cap == False.

4. short_trend_above_trend_line is downgraded.
   - v2 weight: 0.4
   - v3 weight: 0.1
   - It remains a weak score factor and is not a hard condition.

5. long_lower_shadow_hammer is removed from scoring and risk tags.
   - It is no longer treated as a negative risk factor in this strategy.

6. prior_20d_accelerated_huge_volume_bear is removed from scoring and risk tags.
   - It is no longer treated as a negative risk factor in this strategy.

7. T+1 opening gap is not used in this T+0 selection strategy.
   - T+1 opening gap filtering should be handled in the trade strategy layer.
"""

import numpy as np
import pandas as pd

from indicators import add_all_indicators

STRATEGY_NAME = "renko_chart_select_strategy_v3"


DEFAULT_RENKO_CHART_SELECT_WEIGHTS: dict[str, float] = {
    # Condition 2: keep as a medium positive factor.
    "two_day_above_trend_line": 0.8,

    # Condition 3: downgraded from v2 0.4 to v3 0.1.
    # It remains a weak reference factor and is not a hard condition.
    "short_trend_above_trend_line": 0.1,

    # Reversed version of close_below_short_trend_cap.
    # v3 gives positive weight when close_below_short_trend_cap is False.
    "close_above_short_trend_cap": 0.8,

    # Weak auxiliary low-price preference.
    "price_below_50": 0.2,

    # New v3 J-value range.
    # True when J < 0 OR 30 <= J < 50.
    # It is also required as a hard selection condition in v3.
    "j_v3_range": 2.5,

    # Weak auxiliary reference factor.
    "close_above_yellow_ma": 0.2,

    # Condition 8: remains a negative score tag and hard rejection rule.
    "surge_then_shrink_pullback": -3.0,

    # Condition 9: core positive condition.
    # It is also required as a hard selection condition in v3.
    "small_rise_long_red_brick": 3.0,

    # Former risk tag kept as a weak negative factor.
    "prior_20d_shrink_limit_up": -0.3,

    # Former risk tag kept as a negative factor.
    "limit_up_red_brick": -1.0,
}


RENKO_CHART_RISK_RULE_COLUMNS: tuple[str, ...] = (
    "prior_20d_shrink_limit_up",
    "limit_up_red_brick",
)


HARD_REJECTION_COLUMNS: tuple[str, ...] = (
    "surge_then_shrink_pullback",
)


J_VALUE_COLUMN_CANDIDATES: tuple[str, ...] = (
    "kdj_j",
    "j",
    "J",
    "KDJ_J",
    "j_value",
)


def infer_j_column(df: pd.DataFrame) -> str:
    """
    Infer the J-value column generated by the indicator layer.

    Supported candidates:
    - kdj_j
    - j
    - J
    - KDJ_J
    - j_value

    The strategy requires a J-value column because v3 uses:
    J < 0 OR 30 <= J < 50
    as a hard selection condition.
    """
    for col in J_VALUE_COLUMN_CANDIDATES:
        if col in df.columns:
            return col

    raise KeyError(
        "Cannot find J-value column. Expected one of: "
        + ", ".join(J_VALUE_COLUMN_CANDIDATES)
    )


def add_v3_derived_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add v3-specific derived columns.

    Added columns:
    - close_above_short_trend_cap:
      True when close_below_short_trend_cap is False.

    - j_v3_range:
      True when J < 0 OR 30 <= J < 50.

    - j_v3_value:
      The numeric J value used by the v3 range filter.
    """
    out = df.copy()

    if "close_below_short_trend_cap" not in out.columns:
        out["close_below_short_trend_cap"] = False

    out["close_above_short_trend_cap"] = (
        ~out["close_below_short_trend_cap"].fillna(False).astype(bool)
    )

    j_col = infer_j_column(out)
    out["j_v3_value"] = pd.to_numeric(out[j_col], errors="coerce")

    out["j_v3_range"] = (
        (out["j_v3_value"] < 0)
        | ((out["j_v3_value"] >= 30) & (out["j_v3_value"] < 50))
    ).fillna(False)

    return out


def add_strategy_score(
    df: pd.DataFrame,
    weights: dict[str, float] | None = None,
) -> pd.DataFrame:
    """
    Add signed score columns used by renko_chart_select_strategy_v3.

    Scoring details:
    - Each boolean condition contributes its configured signed weight when true.
    - Positive weights increase raw_score.
    - Negative weights reduce raw_score.
    - raw_score is the sum of all active signed condition scores.
    - positive_weight_total is the sum of positive weights only.
    - score_pct = raw_score / positive_weight_total * 100.
    - score_abs_pct = raw_score / absolute_weight_total * 100.
    - score_pct is not used as a hard selection filter in v3.

    Exact default weights:
    - two_day_above_trend_line: 0.8
    - short_trend_above_trend_line: 0.1
    - close_above_short_trend_cap: 0.8
    - price_below_50: 0.2
    - j_v3_range: 2.5
    - close_above_yellow_ma: 0.2
    - surge_then_shrink_pullback: -3.0
    - small_rise_long_red_brick: 3.0
    - prior_20d_shrink_limit_up: -0.3
    - limit_up_red_brick: -1.0
    """
    out = df.copy()
    weights = DEFAULT_RENKO_CHART_SELECT_WEIGHTS if weights is None else weights

    out["raw_score"] = 0.0

    for col, weight in weights.items():
        weight = float(weight)

        if col not in out.columns:
            out[col] = False

        out[f"{col}_weight"] = weight
        out[f"{col}_score"] = np.where(
            out[col].fillna(False).astype(bool),
            weight,
            0.0,
        )
        out["raw_score"] += out[f"{col}_score"]

    positive_weight_total = float(sum(weight for weight in weights.values() if weight > 0)) or 1.0
    absolute_weight_total = float(sum(abs(weight) for weight in weights.values())) or 1.0

    out["positive_weight_total"] = positive_weight_total
    out["absolute_weight_total"] = absolute_weight_total

    out["score_pct"] = out["raw_score"] / positive_weight_total * 100
    out["score_abs_pct"] = out["raw_score"] / absolute_weight_total * 100

    return out


def add_strategy_risk_tags(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add risk tags used for performance attribution.

    v3 risk-tag details:
    - prior_20d_shrink_limit_up is retained as a weak negative score tag.
    - limit_up_red_brick is retained as a negative score tag.
    - long_lower_shadow_hammer is removed from risk tags.
    - prior_20d_accelerated_huge_volume_bear is removed from risk tags.
    - risk_tag_any is true when at least one retained risk condition is true.
    - risk_tag_count counts how many retained risk conditions are true.
    - risk_tags stores triggered condition names as a pipe-separated string.
    - risk_filter_pass is kept as True only for backward compatibility.
    """
    out = df.copy()

    for col in RENKO_CHART_RISK_RULE_COLUMNS:
        if col not in out.columns:
            out[col] = False

    risk_bool_df = out[list(RENKO_CHART_RISK_RULE_COLUMNS)].fillna(False).astype(bool)

    out["risk_tag_any"] = risk_bool_df.any(axis=1)
    out["risk_tag_count"] = risk_bool_df.sum(axis=1)

    out["risk_tags"] = risk_bool_df.apply(
        lambda row: "|".join([col for col, value in row.items() if bool(value)]),
        axis=1,
    )

    # Backward-compatible column.
    # It is not used as a hard rejection filter in v3.
    out["risk_filter_pass"] = True

    return out


def select_renko_chart(
    df: pd.DataFrame,
    n1: int = 4,
    n2: int = 6,
    **kwargs,
) -> pd.DataFrame:
    """
    Build the v3 renko chart selection result from reusable indicators.

    v3 hard selection rules:
    - hard_brick_turn_strong must be true.
    - small_rise_long_red_brick must be true.
    - surge_then_shrink_pullback must be false.
    - j_v3_range must be true:
      J < 0 OR 30 <= J < 50.

    v3 non-filter rules:
    - score_pct is calculated but does not filter candidates.
    - short_trend_above_trend_line is not a hard condition.
    - close_above_short_trend_cap is a positive score factor.
    - long_lower_shadow_hammer is not scored and not tagged as risk.
    - prior_20d_accelerated_huge_volume_bear is not scored and not tagged as risk.
    - T+1 opening gap is not checked here to avoid future-data leakage.

    Output fields:
    - condition9_hard_pass: small_rise_long_red_brick is true.
    - condition8_hard_pass: surge_then_shrink_pullback is false.
    - j_v3_hard_pass: J < 0 OR 30 <= J < 50.
    - selected_score_base: candidate passes the v3 hard rules.
    - selected: same as selected_score_base in v3.
    - score_pct: signed raw_score divided by positive_weight_total.
    - score_abs_pct: signed raw_score divided by absolute_weight_total.
    - risk_tag_any, risk_tag_count, risk_tags: retained risk attribution fields.
    """
    weights = kwargs.get("weights", DEFAULT_RENKO_CHART_SELECT_WEIGHTS)

    required_indicator_columns = {
        "hard_brick_turn_strong",
        "two_day_above_trend_line",
        "short_trend_above_trend_line",
        "close_below_short_trend_cap",
        "price_below_50",
        "close_above_yellow_ma",
        "surge_then_shrink_pullback",
        "small_rise_long_red_brick",
        *RENKO_CHART_RISK_RULE_COLUMNS,
    }

    has_required_indicators = required_indicator_columns.issubset(set(df.columns))
    has_j_column = any(col in df.columns for col in J_VALUE_COLUMN_CANDIDATES)

    if has_required_indicators and has_j_column:
        out = df.copy().sort_values("date").reset_index(drop=True)
    else:
        out = add_all_indicators(df, n1=n1, n2=n2, **kwargs)

    out = add_v3_derived_columns(out)
    out = add_strategy_score(out, weights=weights)
    out = add_strategy_risk_tags(out)

    out["condition9_hard_pass"] = out["small_rise_long_red_brick"].fillna(False).astype(bool)
    out["condition8_hard_pass"] = ~out["surge_then_shrink_pullback"].fillna(False).astype(bool)
    out["j_v3_hard_pass"] = out["j_v3_range"].fillna(False).astype(bool)

    out["selected_score_base"] = (
        out["hard_brick_turn_strong"].fillna(False).astype(bool)
        & out["condition9_hard_pass"]
        & out["condition8_hard_pass"]
        & out["j_v3_hard_pass"]
    ).astype(int)

    out["selected"] = out["selected_score_base"].astype(int)

    out["selection_strategy"] = STRATEGY_NAME

    return out


SELECT_FUNC = select_renko_chart