from __future__ import annotations

"""
Analyze T1 open gap buckets inside oversold rebound pool.

Purpose:
    For oversold_rebound_select_strategy_v0_pool,
    analyze which T1 open gap range is best for:

        T1 open buy -> T2 close sell

Input:
    The detail file generated by compare_oversold_pool_quality_t1_t2.py

Main field:
    t1_open_gap_pct
        = T1 open / T0 close - 1

    t1_open_to_t2_close_ret_pct
        = T2 close / T1 open - 1

Output:
    1. gap bucket summary
    2. gap bucket daily summary
    3. selected detail with gap buckets
"""

import warnings
from pathlib import Path

import numpy as np
import pandas as pd


# =============================================================================
# Fixed paths
# =============================================================================

DETAIL_CSV_PATH = Path(
    r"C:\Users\zyf37\Desktop\BackTest Data\output\oversold_rebound_pool_quality_t1_t2\oversold_rebound_pool_quality_t1_t2_detail.csv"
)

OUTPUT_DIR = Path(
    r"C:\Users\zyf37\Desktop\BackTest Data\output\oversold_rebound_t1_open_gap_bucket"
)


# =============================================================================
# Gap buckets
# =============================================================================

GAP_BINS = [
    -np.inf,
    -5.0,
    -3.0,
    -2.0,
    -1.0,
    0.0,
    1.0,
    2.0,
    3.0,
    5.0,
    np.inf,
]

GAP_LABELS = [
    "gap<-5%",
    "-5%<=gap<-3%",
    "-3%<=gap<-2%",
    "-2%<=gap<-1%",
    "-1%<=gap<0%",
    "0%<=gap<1%",
    "1%<=gap<2%",
    "2%<=gap<3%",
    "3%<=gap<5%",
    "gap>=5%",
]


# =============================================================================
# Optional stronger practical buckets
# =============================================================================

PRACTICAL_GAP_BINS = [
    -np.inf,
    -3.0,
    -2.0,
    -1.0,
    0.5,
    1.5,
    3.0,
    np.inf,
]

PRACTICAL_GAP_LABELS = [
    "deep_low_open_gap<-3%",
    "low_open_-3_to_-2%",
    "low_open_-2_to_-1%",
    "flat_open_-1_to_0.5%",
    "small_high_open_0.5_to_1.5%",
    "high_open_1.5_to_3%",
    "too_high_open_gap>=3%",
]


# =============================================================================
# Helpers
# =============================================================================

def require_columns(df: pd.DataFrame, cols: list[str]) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(
            f"Missing required columns: {missing}\n"
            f"Current columns: {list(df.columns)}"
        )


def to_numeric(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


def build_summary_row(df: pd.DataFrame, group_name: str, bucket: str) -> dict:
    valid = df.dropna(subset=["t1_open_to_t2_close_ret_pct"]).copy()

    row = {
        "group_name": group_name,
        "bucket": bucket,
        "sample_count": len(df),
        "valid_count": len(valid),
        "date_count": valid["date"].nunique() if "date" in valid.columns and len(valid) else 0,
        "symbol_count": valid["symbol"].nunique() if "symbol" in valid.columns and len(valid) else 0,
    }

    if len(valid) == 0:
        return row

    ret = valid["t1_open_to_t2_close_ret_pct"]
    high_ret = valid["t1_open_to_t2_high_ret_pct"]
    low_ret = valid["t1_open_to_t2_low_ret_pct"]
    t1_ret = valid["t1_open_to_t1_close_ret_pct"]
    gap = valid["t1_open_gap_pct"]

    row.update(
        {
            "avg_t1_open_gap_pct": gap.mean(),
            "median_t1_open_gap_pct": gap.median(),

            "t1_t2_mean_ret_pct": ret.mean(),
            "t1_t2_median_ret_pct": ret.median(),
            "t1_t2_p10_ret_pct": ret.quantile(0.10),
            "t1_t2_p25_ret_pct": ret.quantile(0.25),
            "t1_t2_p75_ret_pct": ret.quantile(0.75),
            "t1_t2_p90_ret_pct": ret.quantile(0.90),

            "t1_t2_win_rate_pct": (ret > 0).mean() * 100.0,
            "t1_t2_hit_0_5pct_rate": (ret >= 0.5).mean() * 100.0,
            "t1_t2_hit_1pct_rate": (ret >= 1.0).mean() * 100.0,
            "t1_t2_hit_2pct_rate": (ret >= 2.0).mean() * 100.0,
            "t1_t2_hit_3pct_rate": (ret >= 3.0).mean() * 100.0,
            "t1_t2_hit_5pct_rate": (ret >= 5.0).mean() * 100.0,

            "t1_t2_loss_0_5pct_rate": (ret <= -0.5).mean() * 100.0,
            "t1_t2_loss_1pct_rate": (ret <= -1.0).mean() * 100.0,
            "t1_t2_loss_2pct_rate": (ret <= -2.0).mean() * 100.0,
            "t1_t2_loss_3pct_rate": (ret <= -3.0).mean() * 100.0,
            "t1_t2_loss_5pct_rate": (ret <= -5.0).mean() * 100.0,

            "t2_high_mean_ret_pct": high_ret.mean(),
            "t2_high_hit_1pct_rate": (high_ret >= 1.0).mean() * 100.0,
            "t2_high_hit_2pct_rate": (high_ret >= 2.0).mean() * 100.0,
            "t2_high_hit_3pct_rate": (high_ret >= 3.0).mean() * 100.0,
            "t2_high_hit_5pct_rate": (high_ret >= 5.0).mean() * 100.0,

            "t2_low_mean_ret_pct": low_ret.mean(),
            "t2_low_loss_1pct_rate": (low_ret <= -1.0).mean() * 100.0,
            "t2_low_loss_2pct_rate": (low_ret <= -2.0).mean() * 100.0,
            "t2_low_loss_3pct_rate": (low_ret <= -3.0).mean() * 100.0,
            "t2_low_loss_5pct_rate": (low_ret <= -5.0).mean() * 100.0,

            "t1_intraday_mean_ret_pct": t1_ret.mean(),
            "t1_intraday_median_ret_pct": t1_ret.median(),
            "t1_intraday_win_rate_pct": (t1_ret > 0).mean() * 100.0,
        }
    )

    # Optional columns from selection strategy
    optional_mean_cols = [
        "j",
        "daily_return_pct",
        "close_to_short_trend_ratio",
        "close",
        "t0_close",
        "t1_open",
        "t2_close",
    ]

    for col in optional_mean_cols:
        if col in valid.columns:
            row[f"avg_{col}"] = pd.to_numeric(valid[col], errors="coerce").mean()
            row[f"median_{col}"] = pd.to_numeric(valid[col], errors="coerce").median()

    return row


def summarize_by_bucket(df: pd.DataFrame, bucket_col: str, group_name: str, labels: list[str]) -> pd.DataFrame:
    rows = []

    # ALL row
    rows.append(build_summary_row(df, group_name, "ALL_OVERSOLD_POOL"))

    for label in labels:
        one = df[df[bucket_col].astype(str) == label].copy()
        rows.append(build_summary_row(one, group_name, label))

    result = pd.DataFrame(rows)

    order = {"ALL_OVERSOLD_POOL": -1}
    order.update({label: i for i, label in enumerate(labels)})
    result["_order"] = result["bucket"].map(order)
    result = result.sort_values("_order").drop(columns=["_order"])

    return result


def add_diff_vs_all(summary: pd.DataFrame) -> pd.DataFrame:
    out = summary.copy()

    all_row = out[out["bucket"] == "ALL_OVERSOLD_POOL"]
    if all_row.empty:
        return out

    base = all_row.iloc[0]

    compare_cols = [
        "t1_t2_mean_ret_pct",
        "t1_t2_median_ret_pct",
        "t1_t2_win_rate_pct",
        "t1_t2_hit_1pct_rate",
        "t1_t2_hit_2pct_rate",
        "t1_t2_hit_3pct_rate",
        "t1_t2_loss_1pct_rate",
        "t1_t2_loss_2pct_rate",
        "t1_t2_loss_3pct_rate",
        "t2_high_hit_2pct_rate",
        "t2_low_loss_2pct_rate",
        "t1_intraday_win_rate_pct",
    ]

    for col in compare_cols:
        if col in out.columns:
            out[f"diff_vs_all_{col}"] = out[col] - base[col]

    return out


def build_daily_summary(df: pd.DataFrame, bucket_col: str) -> pd.DataFrame:
    rows = []

    for (date, bucket), one in df.groupby(["date", bucket_col], observed=False, dropna=False):
        valid = one.dropna(subset=["t1_open_to_t2_close_ret_pct"]).copy()

        if len(valid) == 0:
            continue

        ret = valid["t1_open_to_t2_close_ret_pct"]

        rows.append(
            {
                "date": date,
                "bucket_col": bucket_col,
                "bucket": str(bucket),
                "valid_count": len(valid),
                "symbol_count": valid["symbol"].nunique() if "symbol" in valid.columns else np.nan,
                "mean_ret_pct": ret.mean(),
                "median_ret_pct": ret.median(),
                "win_rate_pct": (ret > 0).mean() * 100.0,
                "hit_1pct_rate": (ret >= 1.0).mean() * 100.0,
                "hit_2pct_rate": (ret >= 2.0).mean() * 100.0,
                "loss_1pct_rate": (ret <= -1.0).mean() * 100.0,
                "loss_2pct_rate": (ret <= -2.0).mean() * 100.0,
            }
        )

    return pd.DataFrame(rows)


def print_summary(summary: pd.DataFrame, title: str) -> None:
    show_cols = [
        "bucket",
        "valid_count",
        "avg_t1_open_gap_pct",
        "t1_t2_mean_ret_pct",
        "t1_t2_median_ret_pct",
        "t1_t2_win_rate_pct",
        "t1_t2_hit_1pct_rate",
        "t1_t2_hit_2pct_rate",
        "t1_t2_loss_1pct_rate",
        "t1_t2_loss_2pct_rate",
        "t2_high_hit_2pct_rate",
        "t2_low_loss_2pct_rate",
        "diff_vs_all_t1_t2_mean_ret_pct",
        "diff_vs_all_t1_t2_median_ret_pct",
        "diff_vs_all_t1_t2_win_rate_pct",
        "diff_vs_all_t1_t2_hit_2pct_rate",
        "diff_vs_all_t1_t2_loss_2pct_rate",
    ]

    existing = [c for c in show_cols if c in summary.columns]

    print()
    print("=" * 120)
    print(title)
    print("=" * 120)

    with pd.option_context(
        "display.max_columns", None,
        "display.width", 300,
        "display.float_format", "{:.4f}".format,
    ):
        print(summary[existing].to_string(index=False))


def main() -> None:
    warnings.filterwarnings("ignore", category=FutureWarning)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 120)
    print("Analyze T1 open gap buckets inside oversold rebound pool")
    print("=" * 120)
    print(f"Detail CSV : {DETAIL_CSV_PATH}")
    print(f"Output dir : {OUTPUT_DIR}")

    if not DETAIL_CSV_PATH.exists():
        raise FileNotFoundError(f"Detail CSV not found: {DETAIL_CSV_PATH}")

    df = pd.read_csv(DETAIL_CSV_PATH, low_memory=False)

    require_columns(
        df,
        [
            "date",
            "symbol",
            "is_oversold_pool",
            "t1_open_gap_pct",
            "t1_open_to_t2_close_ret_pct",
            "t1_open_to_t2_high_ret_pct",
            "t1_open_to_t2_low_ret_pct",
            "t1_open_to_t1_close_ret_pct",
        ],
    )

    df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.normalize()

    numeric_cols = [
        "t1_open_gap_pct",
        "t1_open_to_t2_close_ret_pct",
        "t1_open_to_t2_high_ret_pct",
        "t1_open_to_t2_low_ret_pct",
        "t1_open_to_t1_close_ret_pct",
        "j",
        "daily_return_pct",
        "close_to_short_trend_ratio",
        "close",
        "t0_close",
        "t1_open",
        "t2_close",
    ]

    df = to_numeric(df, numeric_cols)

    # Convert is_oversold_pool robustly
    if df["is_oversold_pool"].dtype == object:
        df["is_oversold_pool"] = (
            df["is_oversold_pool"]
            .astype(str)
            .str.lower()
            .isin(["true", "1", "yes"])
        )
    else:
        df["is_oversold_pool"] = df["is_oversold_pool"].astype(bool)

    oversold = df[df["is_oversold_pool"] == True].copy()

    if oversold.empty:
        raise ValueError("No oversold pool rows found in detail CSV.")

    oversold = oversold.dropna(subset=["t1_open_gap_pct"]).copy()

    oversold["t1_open_gap_bucket"] = pd.cut(
        oversold["t1_open_gap_pct"],
        bins=GAP_BINS,
        labels=GAP_LABELS,
        right=False,
    )

    oversold["practical_t1_open_gap_bucket"] = pd.cut(
        oversold["t1_open_gap_pct"],
        bins=PRACTICAL_GAP_BINS,
        labels=PRACTICAL_GAP_LABELS,
        right=False,
    )

    print()
    print("=" * 120)
    print("Loaded oversold pool detail")
    print("=" * 120)
    print(f"Rows              : {len(oversold):,}")
    print(f"Symbols           : {oversold['symbol'].nunique():,}")
    print(f"Date range        : {oversold['date'].min().date()} -> {oversold['date'].max().date()}")
    print(f"T1 gap valid rows : {oversold['t1_open_gap_pct'].notna().sum():,}")

    fine_summary = summarize_by_bucket(
        oversold,
        bucket_col="t1_open_gap_bucket",
        group_name="FINE_T1_OPEN_GAP_BUCKET",
        labels=GAP_LABELS,
    )
    fine_summary = add_diff_vs_all(fine_summary)

    practical_summary = summarize_by_bucket(
        oversold,
        bucket_col="practical_t1_open_gap_bucket",
        group_name="PRACTICAL_T1_OPEN_GAP_BUCKET",
        labels=PRACTICAL_GAP_LABELS,
    )
    practical_summary = add_diff_vs_all(practical_summary)

    fine_daily = build_daily_summary(oversold, "t1_open_gap_bucket")
    practical_daily = build_daily_summary(oversold, "practical_t1_open_gap_bucket")

    detail_out = OUTPUT_DIR / "oversold_rebound_t1_open_gap_bucket_detail.csv"
    fine_summary_out = OUTPUT_DIR / "oversold_rebound_t1_open_gap_fine_summary.csv"
    practical_summary_out = OUTPUT_DIR / "oversold_rebound_t1_open_gap_practical_summary.csv"
    fine_daily_out = OUTPUT_DIR / "oversold_rebound_t1_open_gap_fine_daily_summary.csv"
    practical_daily_out = OUTPUT_DIR / "oversold_rebound_t1_open_gap_practical_daily_summary.csv"

    oversold.to_csv(detail_out, index=False, encoding="utf-8-sig")
    fine_summary.to_csv(fine_summary_out, index=False, encoding="utf-8-sig")
    practical_summary.to_csv(practical_summary_out, index=False, encoding="utf-8-sig")
    fine_daily.to_csv(fine_daily_out, index=False, encoding="utf-8-sig")
    practical_daily.to_csv(practical_daily_out, index=False, encoding="utf-8-sig")

    print_summary(fine_summary, "FINE T1 OPEN GAP BUCKET SUMMARY")
    print_summary(practical_summary, "PRACTICAL T1 OPEN GAP BUCKET SUMMARY")

    print()
    print("=" * 120)
    print("Saved files")
    print("=" * 120)
    print(f"Detail CSV            : {detail_out}")
    print(f"Fine summary CSV      : {fine_summary_out}")
    print(f"Practical summary CSV : {practical_summary_out}")
    print(f"Fine daily CSV        : {fine_daily_out}")
    print(f"Practical daily CSV   : {practical_daily_out}")

    print()
    print("=" * 120)
    print("How to judge")
    print("=" * 120)
    print("Inside oversold rebound pool, focus on:")
    print("1. t1_t2_mean_ret_pct       higher is better")
    print("2. t1_t2_median_ret_pct     higher is better")
    print("3. t1_t2_win_rate_pct       higher is better")
    print("4. t1_t2_hit_2pct_rate      higher is better")
    print("5. t1_t2_loss_2pct_rate     lower is better")
    print()
    print("If low-open / flat-open buckets have higher median and win rate,")
    print("then the trade strategy should buy only in those T1 open gap ranges.")
    print()
    print("If high-open buckets have lower median/win rate and higher loss rate,")
    print("then do not chase high open in oversold rebound model.")


if __name__ == "__main__":
    main()
