from __future__ import annotations

r"""
Batch rebuild B2 T+3 yearly summaries for 2022, 2023, and 2024.

Input:
- Full detail CSV generated by pool_quality_check_b2_t3.py.

Output:
For each year:
- *_summary_complete_YYYY.csv
- *_sell_comparison_YYYY.csv

Default detail path:
C:/Users/zyf37/Desktop/BackTest Data/output/pool_quality_b2_t3_all/b2_confirm_select_strategy_v0_t3_quality_detail.csv

Example:
python .\tools\batch_b2_t3_yearly_summary_2022_2024.py

Or custom path:
python .\tools\batch_b2_t3_yearly_summary_2022_2024.py --detail-path "C:\Users\zyf37\Desktop\BackTest Data\output\pool_quality_b2_t3_all\b2_confirm_select_strategy_v0_t3_quality_detail.csv"
"""

import argparse
from pathlib import Path

import pandas as pd


DEFAULT_DETAIL_PATH = Path(
    r"C:\Users\zyf37\Desktop\BackTest Data\output\pool_quality_b2_t3_all\b2_confirm_select_strategy_v0_t3_quality_detail.csv"
)

DEFAULT_YEARS = [2022, 2023, 2024]


def read_detail(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Detail CSV not found: {path}")

    df = pd.read_csv(path, encoding="utf-8-sig")
    df = df.dropna(how="all").copy()

    if "metric" in df.columns:
        df = df[df["metric"].astype(str).str.strip() != "..."].copy()

    if "signal_date" not in df.columns:
        raise ValueError("Detail CSV must contain signal_date column.")

    df["_signal_date_dt"] = pd.to_datetime(df["signal_date"], errors="coerce").dt.normalize()
    df = df.dropna(subset=["_signal_date_dt"]).copy()
    return df.reset_index(drop=True)


def filter_year(df: pd.DataFrame, year: int) -> pd.DataFrame:
    start = pd.Timestamp(f"{year}-01-01")
    end = pd.Timestamp(f"{year}-12-31")
    out = df[(df["_signal_date_dt"] >= start) & (df["_signal_date_dt"] <= end)].copy()
    out = out.drop(columns=["_signal_date_dt"], errors="ignore")
    return out.reset_index(drop=True)


def ensure_return_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if "buy_t1_open" not in df.columns:
        raise ValueError("Missing required column: buy_t1_open")

    price_to_ret = {
        "ret_t1_open_to_t2_open_pct": "t2_open",
        "ret_t1_open_to_t2_close_pct": "t2_close",
        "ret_t1_open_to_t3_open_pct": "t3_open",
        "ret_t1_open_to_t3_close_pct": "t3_close",
    }

    buy = pd.to_numeric(df["buy_t1_open"], errors="coerce")

    for ret_col, price_col in price_to_ret.items():
        if ret_col not in df.columns:
            if price_col not in df.columns:
                raise ValueError(f"Cannot rebuild {ret_col}; missing price column: {price_col}")
            sell = pd.to_numeric(df[price_col], errors="coerce")
            df[ret_col] = (sell / buy - 1.0) * 100.0

    return df


def ensure_win_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    ret_map = {
        "win_t2_open": "ret_t1_open_to_t2_open_pct",
        "win_t2_close": "ret_t1_open_to_t2_close_pct",
        "win_t3_open": "ret_t1_open_to_t3_open_pct",
        "win_t3_close": "ret_t1_open_to_t3_close_pct",
    }

    for win_col, ret_col in ret_map.items():
        ret = pd.to_numeric(df[ret_col], errors="coerce")
        df[win_col] = ret > 0

    return df


def ensure_opportunity_drawdown_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if len(df) == 0:
        return df

    buy = pd.to_numeric(df["buy_t1_open"], errors="coerce")

    required_price_cols = [
        "t1_high", "t1_low",
        "t2_high", "t2_low",
        "t3_high", "t3_low",
    ]
    for c in required_price_cols:
        if c not in df.columns:
            raise ValueError(f"Missing required price column: {c}")
        df[c] = pd.to_numeric(df[c], errors="coerce")

    if "max_opportunity_t1_t2_pct" not in df.columns:
        high_t1_t2 = df[["t1_high", "t2_high"]].max(axis=1)
        df["max_opportunity_t1_t2_pct"] = (high_t1_t2 / buy - 1.0) * 100.0

    if "max_drawdown_t1_t2_pct" not in df.columns:
        low_t1_t2 = df[["t1_low", "t2_low"]].min(axis=1)
        df["max_drawdown_t1_t2_pct"] = (low_t1_t2 / buy - 1.0) * 100.0

    if "max_opportunity_t1_t3_pct" not in df.columns:
        high_t1_t3 = df[["t1_high", "t2_high", "t3_high"]].max(axis=1)
        df["max_opportunity_t1_t3_pct"] = (high_t1_t3 / buy - 1.0) * 100.0

    if "max_drawdown_t1_t3_pct" not in df.columns:
        low_t1_t3 = df[["t1_low", "t2_low", "t3_low"]].min(axis=1)
        df["max_drawdown_t1_t3_pct"] = (low_t1_t3 / buy - 1.0) * 100.0

    for horizon, opp_col, dd_col in [
        ("t1_t2", "max_opportunity_t1_t2_pct", "max_drawdown_t1_t2_pct"),
        ("t1_t3", "max_opportunity_t1_t3_pct", "max_drawdown_t1_t3_pct"),
    ]:
        opp = pd.to_numeric(df[opp_col], errors="coerce")
        dd = pd.to_numeric(df[dd_col], errors="coerce")

        for x in [2, 3, 5]:
            df[f"hit_plus_{x}pct_{horizon}"] = opp >= x
            df[f"hit_minus_{x}pct_{horizon}"] = dd <= -x

    return df


def clean_numeric_rows(df: pd.DataFrame) -> pd.DataFrame:
    required = [
        "buy_t1_open",
        "ret_t1_open_to_t2_open_pct",
        "ret_t1_open_to_t2_close_pct",
        "ret_t1_open_to_t3_open_pct",
        "ret_t1_open_to_t3_close_pct",
    ]

    out = df.copy()
    for c in required:
        out[c] = pd.to_numeric(out[c], errors="coerce")

    out = out.dropna(subset=required).copy()
    return out.reset_index(drop=True)


def mean_pct_bool(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.Series(df[col]).astype(bool).mean()) * 100.0, 6)


def mean_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").mean()), 6)


def median_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").median()), 6)


def max_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").max()), 6)


def min_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").min()), 6)


def build_complete_summary(df: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict] = []

    rows.append({"metric": "trade_count", "value": int(len(df))})

    sell_modes = [
        ("t2_open", "win_t2_open", "ret_t1_open_to_t2_open_pct"),
        ("t2_close", "win_t2_close", "ret_t1_open_to_t2_close_pct"),
        ("t3_open", "win_t3_open", "ret_t1_open_to_t3_open_pct"),
        ("t3_close", "win_t3_close", "ret_t1_open_to_t3_close_pct"),
    ]

    for label, win_col, ret_col in sell_modes:
        rows.extend(
            [
                {"metric": f"{label}_win_rate_pct", "value": mean_pct_bool(df, win_col)},
                {"metric": f"{label}_avg_ret_pct", "value": mean_num(df, ret_col)},
                {"metric": f"{label}_median_ret_pct", "value": median_num(df, ret_col)},
                {"metric": f"{label}_best_ret_pct", "value": max_num(df, ret_col)},
                {"metric": f"{label}_worst_ret_pct", "value": min_num(df, ret_col)},
            ]
        )

    for horizon, opp_col, dd_col in [
        ("t1_t2", "max_opportunity_t1_t2_pct", "max_drawdown_t1_t2_pct"),
        ("t1_t3", "max_opportunity_t1_t3_pct", "max_drawdown_t1_t3_pct"),
    ]:
        rows.extend(
            [
                {"metric": f"{horizon}_hit_plus_2pct_rate_pct", "value": mean_pct_bool(df, f"hit_plus_2pct_{horizon}")},
                {"metric": f"{horizon}_hit_plus_3pct_rate_pct", "value": mean_pct_bool(df, f"hit_plus_3pct_{horizon}")},
                {"metric": f"{horizon}_hit_plus_5pct_rate_pct", "value": mean_pct_bool(df, f"hit_plus_5pct_{horizon}")},
                {"metric": f"{horizon}_hit_minus_2pct_rate_pct", "value": mean_pct_bool(df, f"hit_minus_2pct_{horizon}")},
                {"metric": f"{horizon}_hit_minus_3pct_rate_pct", "value": mean_pct_bool(df, f"hit_minus_3pct_{horizon}")},
                {"metric": f"{horizon}_hit_minus_5pct_rate_pct", "value": mean_pct_bool(df, f"hit_minus_5pct_{horizon}")},
                {"metric": f"{horizon}_avg_max_opportunity_pct", "value": mean_num(df, opp_col)},
                {"metric": f"{horizon}_median_max_opportunity_pct", "value": median_num(df, opp_col)},
                {"metric": f"{horizon}_avg_max_drawdown_pct", "value": mean_num(df, dd_col)},
                {"metric": f"{horizon}_median_max_drawdown_pct", "value": median_num(df, dd_col)},
            ]
        )

    return pd.DataFrame(rows)


def build_sell_comparison(summary: pd.DataFrame) -> pd.DataFrame:
    m = dict(zip(summary["metric"], summary["value"]))

    rows = []
    for label in ["t2_open", "t2_close", "t3_open", "t3_close"]:
        rows.append(
            {
                "sell_mode": label,
                "win_rate_pct": m.get(f"{label}_win_rate_pct", 0),
                "avg_ret_pct": m.get(f"{label}_avg_ret_pct", 0),
                "median_ret_pct": m.get(f"{label}_median_ret_pct", 0),
                "best_ret_pct": m.get(f"{label}_best_ret_pct", 0),
                "worst_ret_pct": m.get(f"{label}_worst_ret_pct", 0),
            }
        )

    return pd.DataFrame(rows)


def process_year(detail: pd.DataFrame, year: int, output_dir: Path, stem: str) -> dict:
    year_df = filter_year(detail, year)
    year_df = ensure_return_columns(year_df)
    year_df = ensure_win_columns(year_df)
    year_df = ensure_opportunity_drawdown_columns(year_df)
    year_df = clean_numeric_rows(year_df)

    summary = build_complete_summary(year_df)
    comparison = build_sell_comparison(summary)

    summary_path = output_dir / f"{stem}_summary_complete_{year}.csv"
    comparison_path = output_dir / f"{stem}_sell_comparison_{year}.csv"

    summary.to_csv(summary_path, index=False, encoding="utf-8-sig")
    comparison.to_csv(comparison_path, index=False, encoding="utf-8-sig")

    best_avg_row = comparison.sort_values("avg_ret_pct", ascending=False).head(1).iloc[0]
    best_win_row = comparison.sort_values("win_rate_pct", ascending=False).head(1).iloc[0]

    return {
        "year": year,
        "trade_count": int(len(year_df)),
        "best_avg_sell_mode": best_avg_row["sell_mode"],
        "best_avg_ret_pct": best_avg_row["avg_ret_pct"],
        "best_win_sell_mode": best_win_row["sell_mode"],
        "best_win_rate_pct": best_win_row["win_rate_pct"],
        "summary_path": str(summary_path),
        "comparison_path": str(comparison_path),
    }


def parse_years(raw: str) -> list[int]:
    if not raw.strip():
        return DEFAULT_YEARS
    return [int(x.strip()) for x in raw.split(",") if x.strip()]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Batch yearly B2 T+3 summary for 2022-2024.")
    parser.add_argument("--detail-path", type=Path, default=DEFAULT_DETAIL_PATH)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--years", default="2022,2023,2024", help="Comma-separated years, default: 2022,2023,2024")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    detail = read_detail(args.detail_path)

    output_dir = args.output_dir
    if output_dir is None:
        output_dir = args.detail_path.parent / "yearly_summary_2022_2024"

    output_dir.mkdir(parents=True, exist_ok=True)

    stem = args.detail_path.stem.replace("_detail", "")
    years = parse_years(args.years)

    print("=" * 104)
    print("Batch B2 T+3 Yearly Summary")
    print("=" * 104)
    print(f"Detail input : {args.detail_path}")
    print(f"Output dir   : {output_dir}")
    print(f"Years        : {years}")
    print(f"Raw rows     : {len(detail):,}")
    print("-" * 104)

    rows = []
    for year in years:
        result = process_year(detail, year, output_dir, stem)
        rows.append(result)

        print(
            f"{year} | trades={result['trade_count']:,} | "
            f"best_avg={result['best_avg_sell_mode']} {result['best_avg_ret_pct']}% | "
            f"best_win={result['best_win_sell_mode']} {result['best_win_rate_pct']}%"
        )

    index_df = pd.DataFrame(rows)
    index_path = output_dir / f"{stem}_yearly_index.csv"
    index_df.to_csv(index_path, index=False, encoding="utf-8-sig")

    print("-" * 104)
    print(f"Index file: {index_path}")
    print("Done")
    print("=" * 104)


if __name__ == "__main__":
    main()
