from __future__ import annotations

r"""
Fix / rebuild B2 T+3 quality summary from detail CSV, with optional date range filter.

Purpose:
- Read the detail file generated by pool_quality_check_b2_t3.py.
- Optionally filter by signal_date.
- Recalculate a complete summary.
- Avoid any literal "..." rows.
- Output all metrics for:
    1. T+2 open sell
    2. T+2 close sell
    3. T+3 open sell
    4. T+3 close sell
    5. T+1~T+2 opportunity / drawdown
    6. T+1~T+3 opportunity / drawdown

Default input:
C:/Users/zyf37/Desktop/BackTest Data/output/pool_quality_b2_t3/b2_confirm_select_strategy_v0_t3_quality_detail.csv

Example:
python .\tools\fix_b2_t3_summary_complete.py ^
  --detail-path "C:\Users\zyf37\Desktop\BackTest Data\output\pool_quality_b2_t3\b2_confirm_select_strategy_v0_t3_quality_detail.csv" ^
  --start-date 2025-01-01 ^
  --end-date 2025-12-31
"""

import argparse
from pathlib import Path

import pandas as pd


DEFAULT_DETAIL_PATH = Path(
    r"C:\Users\zyf37\Desktop\BackTest Data\output\pool_quality_b2_t3\b2_confirm_select_strategy_v0_t3_quality_detail.csv"
)


def read_detail(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Detail CSV not found: {path}")

    df = pd.read_csv(path, encoding="utf-8-sig")
    df = df.dropna(how="all").copy()

    # Remove accidental summary/ellipsis rows if someone passed a bad CSV.
    if "metric" in df.columns:
        df = df[df["metric"].astype(str).str.strip() != "..."].copy()

    return df


def filter_by_signal_date(
    df: pd.DataFrame,
    start_date: str | None = None,
    end_date: str | None = None,
) -> pd.DataFrame:
    """
    Filter detail rows by signal_date.

    Expected column:
        signal_date

    If signal_date is missing, this function raises an error because date range
    filtering would be ambiguous.
    """
    if not start_date and not end_date:
        return df.copy()

    if "signal_date" not in df.columns:
        raise ValueError(
            "Date range filter requires a 'signal_date' column in detail CSV."
        )

    out = df.copy()
    out["_signal_date_dt"] = pd.to_datetime(out["signal_date"], errors="coerce").dt.normalize()
    out = out.dropna(subset=["_signal_date_dt"]).copy()

    if start_date:
        start = pd.to_datetime(start_date).normalize()
        out = out[out["_signal_date_dt"] >= start].copy()

    if end_date:
        end = pd.to_datetime(end_date).normalize()
        out = out[out["_signal_date_dt"] <= end].copy()

    out = out.drop(columns=["_signal_date_dt"])
    return out.reset_index(drop=True)


def ensure_return_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Recreate return columns from price columns if they are missing.
    """
    df = df.copy()

    if "buy_t1_open" not in df.columns:
        raise ValueError("Missing required column: buy_t1_open")

    price_to_ret = {
        "ret_t1_open_to_t2_open_pct": "t2_open",
        "ret_t1_open_to_t2_close_pct": "t2_close",
        "ret_t1_open_to_t3_open_pct": "t3_open",
        "ret_t1_open_to_t3_close_pct": "t3_close",
    }

    buy = pd.to_numeric(df["buy_t1_open"], errors="coerce")

    for ret_col, price_col in price_to_ret.items():
        if ret_col not in df.columns:
            if price_col not in df.columns:
                raise ValueError(f"Cannot rebuild {ret_col}; missing price column: {price_col}")
            sell = pd.to_numeric(df[price_col], errors="coerce")
            df[ret_col] = (sell / buy - 1.0) * 100.0

    return df


def ensure_win_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    ret_map = {
        "win_t2_open": "ret_t1_open_to_t2_open_pct",
        "win_t2_close": "ret_t1_open_to_t2_close_pct",
        "win_t3_open": "ret_t1_open_to_t3_open_pct",
        "win_t3_close": "ret_t1_open_to_t3_close_pct",
    }

    for win_col, ret_col in ret_map.items():
        ret = pd.to_numeric(df[ret_col], errors="coerce")
        df[win_col] = ret > 0

    return df


def ensure_opportunity_drawdown_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Recreate T+1~T+2 and T+1~T+3 opportunity/drawdown columns if missing.
    """
    df = df.copy()
    buy = pd.to_numeric(df["buy_t1_open"], errors="coerce")

    required_price_cols = [
        "t1_high", "t1_low",
        "t2_high", "t2_low",
        "t3_high", "t3_low",
    ]
    for c in required_price_cols:
        if c not in df.columns:
            raise ValueError(f"Missing required price column: {c}")
        df[c] = pd.to_numeric(df[c], errors="coerce")

    if "max_opportunity_t1_t2_pct" not in df.columns:
        high_t1_t2 = df[["t1_high", "t2_high"]].max(axis=1)
        df["max_opportunity_t1_t2_pct"] = (high_t1_t2 / buy - 1.0) * 100.0

    if "max_drawdown_t1_t2_pct" not in df.columns:
        low_t1_t2 = df[["t1_low", "t2_low"]].min(axis=1)
        df["max_drawdown_t1_t2_pct"] = (low_t1_t2 / buy - 1.0) * 100.0

    if "max_opportunity_t1_t3_pct" not in df.columns:
        high_t1_t3 = df[["t1_high", "t2_high", "t3_high"]].max(axis=1)
        df["max_opportunity_t1_t3_pct"] = (high_t1_t3 / buy - 1.0) * 100.0

    if "max_drawdown_t1_t3_pct" not in df.columns:
        low_t1_t3 = df[["t1_low", "t2_low", "t3_low"]].min(axis=1)
        df["max_drawdown_t1_t3_pct"] = (low_t1_t3 / buy - 1.0) * 100.0

    thresholds = [2, 3, 5]
    for horizon, opp_col, dd_col in [
        ("t1_t2", "max_opportunity_t1_t2_pct", "max_drawdown_t1_t2_pct"),
        ("t1_t3", "max_opportunity_t1_t3_pct", "max_drawdown_t1_t3_pct"),
    ]:
        opp = pd.to_numeric(df[opp_col], errors="coerce")
        dd = pd.to_numeric(df[dd_col], errors="coerce")

        for x in thresholds:
            df[f"hit_plus_{x}pct_{horizon}"] = opp >= x
            df[f"hit_minus_{x}pct_{horizon}"] = dd <= -x

    return df


def clean_numeric_rows(df: pd.DataFrame) -> pd.DataFrame:
    """
    Keep rows that have enough real trade data.
    """
    required = [
        "buy_t1_open",
        "ret_t1_open_to_t2_open_pct",
        "ret_t1_open_to_t2_close_pct",
        "ret_t1_open_to_t3_open_pct",
        "ret_t1_open_to_t3_close_pct",
    ]

    out = df.copy()
    for c in required:
        out[c] = pd.to_numeric(out[c], errors="coerce")

    out = out.dropna(subset=required).copy()
    return out.reset_index(drop=True)


def mean_pct_bool(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.Series(df[col]).astype(bool).mean()) * 100.0, 6)


def mean_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").mean()), 6)


def median_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").median()), 6)


def max_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").max()), 6)


def min_num(df: pd.DataFrame, col: str) -> float:
    if col not in df.columns or len(df) == 0:
        return 0.0
    return round(float(pd.to_numeric(df[col], errors="coerce").min()), 6)


def build_complete_summary(df: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict] = []

    rows.append({"metric": "trade_count", "value": int(len(df))})

    sell_modes = [
        ("t2_open", "win_t2_open", "ret_t1_open_to_t2_open_pct"),
        ("t2_close", "win_t2_close", "ret_t1_open_to_t2_close_pct"),
        ("t3_open", "win_t3_open", "ret_t1_open_to_t3_open_pct"),
        ("t3_close", "win_t3_close", "ret_t1_open_to_t3_close_pct"),
    ]

    for label, win_col, ret_col in sell_modes:
        rows.extend(
            [
                {"metric": f"{label}_win_rate_pct", "value": mean_pct_bool(df, win_col)},
                {"metric": f"{label}_avg_ret_pct", "value": mean_num(df, ret_col)},
                {"metric": f"{label}_median_ret_pct", "value": median_num(df, ret_col)},
                {"metric": f"{label}_best_ret_pct", "value": max_num(df, ret_col)},
                {"metric": f"{label}_worst_ret_pct", "value": min_num(df, ret_col)},
            ]
        )

    horizons = [
        ("t1_t2", "max_opportunity_t1_t2_pct", "max_drawdown_t1_t2_pct"),
        ("t1_t3", "max_opportunity_t1_t3_pct", "max_drawdown_t1_t3_pct"),
    ]

    for horizon, opp_col, dd_col in horizons:
        rows.extend(
            [
                {"metric": f"{horizon}_hit_plus_2pct_rate_pct", "value": mean_pct_bool(df, f"hit_plus_2pct_{horizon}")},
                {"metric": f"{horizon}_hit_plus_3pct_rate_pct", "value": mean_pct_bool(df, f"hit_plus_3pct_{horizon}")},
                {"metric": f"{horizon}_hit_plus_5pct_rate_pct", "value": mean_pct_bool(df, f"hit_plus_5pct_{horizon}")},
                {"metric": f"{horizon}_hit_minus_2pct_rate_pct", "value": mean_pct_bool(df, f"hit_minus_2pct_{horizon}")},
                {"metric": f"{horizon}_hit_minus_3pct_rate_pct", "value": mean_pct_bool(df, f"hit_minus_3pct_{horizon}")},
                {"metric": f"{horizon}_hit_minus_5pct_rate_pct", "value": mean_pct_bool(df, f"hit_minus_5pct_{horizon}")},
                {"metric": f"{horizon}_avg_max_opportunity_pct", "value": mean_num(df, opp_col)},
                {"metric": f"{horizon}_median_max_opportunity_pct", "value": median_num(df, opp_col)},
                {"metric": f"{horizon}_avg_max_drawdown_pct", "value": mean_num(df, dd_col)},
                {"metric": f"{horizon}_median_max_drawdown_pct", "value": median_num(df, dd_col)},
            ]
        )

    return pd.DataFrame(rows)


def build_sell_comparison(summary: pd.DataFrame) -> pd.DataFrame:
    m = dict(zip(summary["metric"], summary["value"]))

    rows = []
    for label in ["t2_open", "t2_close", "t3_open", "t3_close"]:
        rows.append(
            {
                "sell_mode": label,
                "win_rate_pct": m.get(f"{label}_win_rate_pct", 0),
                "avg_ret_pct": m.get(f"{label}_avg_ret_pct", 0),
                "median_ret_pct": m.get(f"{label}_median_ret_pct", 0),
                "best_ret_pct": m.get(f"{label}_best_ret_pct", 0),
                "worst_ret_pct": m.get(f"{label}_worst_ret_pct", 0),
            }
        )

    return pd.DataFrame(rows)


def make_output_paths(
    detail_path: Path,
    start_date: str | None,
    end_date: str | None,
    output_summary_path: Path | None,
    output_comparison_path: Path | None,
) -> tuple[Path, Path]:
    date_suffix = ""
    if start_date or end_date:
        s = start_date or "START"
        e = end_date or "END"
        date_suffix = f"_{s}_to_{e}".replace("-", "")

    if output_summary_path is None:
        output_summary_path = detail_path.with_name(
            detail_path.stem.replace("_detail", f"_summary_complete{date_suffix}") + ".csv"
        )

    if output_comparison_path is None:
        output_comparison_path = detail_path.with_name(
            detail_path.stem.replace("_detail", f"_sell_comparison{date_suffix}") + ".csv"
        )

    return output_summary_path, output_comparison_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fix B2 T+3 summary from detail CSV, with date range filter.")
    parser.add_argument("--detail-path", type=Path, default=DEFAULT_DETAIL_PATH)
    parser.add_argument("--start-date", default=None, help="Filter by signal_date, example: 2025-01-01")
    parser.add_argument("--end-date", default=None, help="Filter by signal_date, example: 2025-12-31")
    parser.add_argument("--output-summary-path", type=Path, default=None)
    parser.add_argument("--output-comparison-path", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    raw_detail = read_detail(args.detail_path)
    filtered_detail = filter_by_signal_date(raw_detail, args.start_date, args.end_date)

    detail = ensure_return_columns(filtered_detail)
    detail = ensure_win_columns(detail)
    detail = ensure_opportunity_drawdown_columns(detail)
    detail = clean_numeric_rows(detail)

    summary = build_complete_summary(detail)
    comparison = build_sell_comparison(summary)

    output_summary_path, output_comparison_path = make_output_paths(
        detail_path=args.detail_path,
        start_date=args.start_date,
        end_date=args.end_date,
        output_summary_path=args.output_summary_path,
        output_comparison_path=args.output_comparison_path,
    )

    output_summary_path.parent.mkdir(parents=True, exist_ok=True)
    output_comparison_path.parent.mkdir(parents=True, exist_ok=True)

    summary.to_csv(output_summary_path, index=False, encoding="utf-8-sig")
    comparison.to_csv(output_comparison_path, index=False, encoding="utf-8-sig")

    print("=" * 104)
    print("B2 T+3 Summary Fixed")
    print("=" * 104)
    print(f"Detail input          : {args.detail_path}")
    print(f"Date range            : {args.start_date or 'ALL'} -> {args.end_date or 'ALL'}")
    print(f"Raw detail rows        : {len(raw_detail):,}")
    print(f"Filtered detail rows   : {len(filtered_detail):,}")
    print(f"Valid trade rows       : {len(detail):,}")
    print(f"Summary output        : {output_summary_path}")
    print(f"Comparison output     : {output_comparison_path}")
    print("-" * 104)
    print("Sell comparison")
    print("-" * 104)
    print(comparison.to_string(index=False))
    print("-" * 104)
    print("Complete summary")
    print("-" * 104)
    for _, row in summary.iterrows():
        print(f"{str(row['metric']).ljust(52)} : {row['value']}")
    print("=" * 104)


if __name__ == "__main__":
    main()
