from __future__ import annotations

r"""
Train XGBoost model to predict B2 strategy T+2 close return.

This version is adapted to the current B2 pool column names.

It supports feature aliases such as:
- J -> b2_j
- pct_change_close -> daily_return_pct
- volume_ratio_prev -> b2_volume_ratio
- b1_days_ago_for_b2 -> b1_days_ago
- b2_quality_score -> score

Target:
- ret_t1_open_to_t2_close_pct

Input should be the trade detail generated by:
python .\tools\compare_b2_v0_v1_v2_yearly.py --save-detail

Default input:
C:/Users/zyf37/Desktop/BackTest Data/output/b2_v0_v1_v2_yearly_compare/b2_v0_v1_v2_trade_detail.csv

Default output:
C:/Users/zyf37/Desktop/BackTest Data/output/xgb_b2_t2_return_alias_fixed

Install:
python -m pip install xgboost scikit-learn pandas numpy tqdm joblib
"""

import argparse
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

try:
    from tqdm import tqdm
except Exception:
    tqdm = None


DEFAULT_DETAIL_PATH = Path(
    r"C:\Users\zyf37\Desktop\BackTest Data\output\b2_v0_v1_v2_yearly_compare\b2_v0_v1_v2_trade_detail.csv"
)

DEFAULT_OUTPUT_DIR = Path(
    r"C:\Users\zyf37\Desktop\BackTest Data\output\xgb_b2_t2_return_alias_fixed"
)

TARGET_COL = "ret_t1_open_to_t2_close_pct"


# Canonical feature name -> possible source columns in your current data.
FEATURE_ALIAS_MAP: dict[str, list[str]] = {
    "b2_j": ["b2_j_value", "J", "j"],
    "b1_days_ago": ["b1_days_ago", "b1_days_ago_for_b2"],
    "b2_volume_ratio": ["b2_volume_ratio", "volume_ratio_prev", "volume_ratio_ma5"],
    "upper_shadow_ratio": ["upper_shadow_ratio"],
    "daily_return_pct": ["daily_return_pct", "pct_change_close"],
    "b2_quality_score": ["b2_quality_score", "score"],
    "position_in_range_20": ["position_in_range_20"],
    "range_width_20": ["range_width_20"],
    "distance_to_previous_n_low": ["distance_to_previous_n_low"],
    "distance_to_ma20": ["distance_to_ma20"],
    "distance_to_bbi": ["distance_to_bbi"],
    "distance_to_yellow": ["distance_to_yellow"],
    "volume_ratio_ma5": ["volume_ratio_ma5"],
    "volume_q20_20": ["volume_q20_20"],
    "b2_double_volume": ["b2_double_volume"],
    "b2_sky_volume": ["b2_sky_volume"],
    "b2_j_high_zone": ["b2_j_high_zone"],
    "b2_tiny_upper_shadow": ["b2_tiny_upper_shadow"],
    "b2_upper_shadow_warning": ["b2_upper_shadow_warning"],
}


def progress(iterable, desc: str = "", total: int | None = None):
    if tqdm is not None:
        return tqdm(iterable, desc=desc, total=total)
    return iterable


def parse_year_list(raw: str) -> list[int]:
    if not raw.strip():
        return []
    return [int(x.strip()) for x in raw.split(",") if x.strip()]


def normalize_strategy_name(s: object) -> str:
    x = str(s).strip()
    if x in {"v0", "b2_confirm_select_strategy_v0"}:
        return "v0"
    if x in {"v1", "b2_confirm_select_strategy_v1"}:
        return "v1"
    if x in {"v2", "b2_confirm_select_strategy_v2"}:
        return "v2"
    return x


def read_detail(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Detail CSV not found: {path}")

    print("=" * 100)
    print("Loading detail")
    print("=" * 100)
    print(f"Path: {path}")

    df = pd.read_csv(path, encoding="utf-8-sig")
    print(f"Raw rows: {len(df):,}")
    print(f"Columns : {len(df.columns):,}")
    print("-" * 100)

    return df


def add_alias_features(df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    out = df.copy()
    used_features: list[str] = []

    print("=" * 100)
    print("Feature alias mapping")
    print("=" * 100)

    for canonical, candidates in FEATURE_ALIAS_MAP.items():
        source_col = None
        for c in candidates:
            if c in out.columns:
                source_col = c
                break

        if source_col is None:
            print(f"[MISS] {canonical:<28} <- {candidates}")
            continue

        s = out[source_col]

        # Bool features to int.
        if s.dtype == bool or str(s.dtype).lower() == "bool":
            out[canonical] = s.astype(int)
        else:
            # Some CSV boolean columns may be strings.
            if s.astype(str).str.lower().isin(["true", "false"]).all():
                out[canonical] = s.astype(str).str.lower().map({"true": 1, "false": 0})
            else:
                out[canonical] = pd.to_numeric(s, errors="coerce")

        used_features.append(canonical)
        print(f"[ OK ] {canonical:<28} <- {source_col}")

    print("-" * 100)
    return out, used_features


def prepare_data(df: pd.DataFrame, strategy: str) -> tuple[pd.DataFrame, list[str]]:
    print("=" * 100)
    print("Preparing data")
    print("=" * 100)

    required_cols = ["strategy", "signal_date", TARGET_COL]
    missing_required = [c for c in required_cols if c not in df.columns]
    if missing_required:
        raise ValueError(f"Missing required columns: {missing_required}")

    df = df.copy()
    df["strategy_norm"] = df["strategy"].map(normalize_strategy_name)

    print("Strategy distribution:")
    print(df["strategy_norm"].value_counts(dropna=False).to_string())
    print("-" * 100)

    df = df[df["strategy_norm"] == strategy].copy()
    print(f"After strategy filter ({strategy}) rows: {len(df):,}")

    if len(df) == 0:
        raise ValueError(f"No rows after filtering strategy={strategy}.")

    df["signal_date"] = pd.to_datetime(df["signal_date"], errors="coerce")
    df = df.dropna(subset=["signal_date"]).copy()
    df["year"] = df["signal_date"].dt.year

    print("Year distribution after strategy filter:")
    print(df["year"].value_counts(dropna=False).sort_index().to_string())
    print("-" * 100)

    df, feature_cols = add_alias_features(df)

    if not feature_cols:
        raise ValueError("No usable feature columns found after alias mapping.")

    # Drop all-NaN or constant features.
    usable_features: list[str] = []
    dropped_features: list[str] = []

    for c in feature_cols:
        non_na = df[c].dropna()
        if len(non_na) == 0:
            dropped_features.append(f"{c}__all_nan")
            continue
        if non_na.nunique() <= 1:
            dropped_features.append(f"{c}__constant")
            continue
        usable_features.append(c)

    feature_cols = usable_features

    print("Dropped unusable features:")
    if dropped_features:
        for x in dropped_features:
            print(f"  - {x}")
    else:
        print("  None")
    print("-" * 100)

    if not feature_cols:
        raise ValueError("All features are unusable after checking all-NaN/constant.")

    print("Final feature columns used:")
    for c in feature_cols:
        print(f"  - {c}")
    print("-" * 100)

    keep_cols = ["symbol", "signal_date", "year", TARGET_COL] + feature_cols
    keep_cols = [c for c in keep_cols if c in df.columns]
    df = df[keep_cols].copy()

    df[TARGET_COL] = pd.to_numeric(df[TARGET_COL], errors="coerce")

    missing_stat = df[feature_cols + [TARGET_COL]].isna().sum().sort_values(ascending=False)
    print("Missing value count before dropna:")
    print(missing_stat.to_string())
    print("-" * 100)

    before = len(df)
    df = df.dropna(subset=feature_cols + [TARGET_COL]).copy()
    after = len(df)

    print(f"Rows before dropna: {before:,}")
    print(f"Rows after dropna : {after:,}")
    print(f"Dropped rows      : {before - after:,}")
    print("-" * 100)

    if len(df) == 0:
        raise ValueError("No usable rows after dropna.")

    return df.reset_index(drop=True), feature_cols


def split_by_years(
    df: pd.DataFrame,
    train_years: list[int],
    valid_years: list[int],
    test_years: list[int],
    observe_years: list[int],
) -> dict[str, pd.DataFrame]:
    splits = {
        "train": df[df["year"].isin(train_years)].copy(),
        "valid": df[df["year"].isin(valid_years)].copy(),
        "test": df[df["year"].isin(test_years)].copy(),
        "observe": df[df["year"].isin(observe_years)].copy(),
    }

    print("=" * 100)
    print("Data split")
    print("=" * 100)
    print(f"train years  : {train_years} | rows={len(splits['train']):,}")
    print(f"valid years  : {valid_years} | rows={len(splits['valid']):,}")
    print(f"test years   : {test_years} | rows={len(splits['test']):,}")
    print(f"observe years: {observe_years} | rows={len(splits['observe']):,}")
    print("-" * 100)

    if len(splits["train"]) == 0:
        raise ValueError("Train set is empty.")

    return splits


def train_model(
    train_df: pd.DataFrame,
    valid_df: pd.DataFrame,
    feature_cols: list[str],
    args: argparse.Namespace,
) -> XGBRegressor:
    print("=" * 100)
    print("Training XGBoost model")
    print("=" * 100)

    model = XGBRegressor(
        n_estimators=args.n_estimators,
        max_depth=args.max_depth,
        learning_rate=args.learning_rate,
        subsample=args.subsample,
        colsample_bytree=args.colsample_bytree,
        min_child_weight=args.min_child_weight,
        reg_alpha=args.reg_alpha,
        reg_lambda=args.reg_lambda,
        objective="reg:squarederror",
        random_state=args.random_state,
        n_jobs=args.n_jobs,
        tree_method="hist",
    )

    if len(valid_df) > 0:
        model.fit(
            train_df[feature_cols],
            train_df[TARGET_COL],
            eval_set=[(valid_df[feature_cols], valid_df[TARGET_COL])],
            verbose=args.xgb_verbose,
        )
    else:
        model.fit(
            train_df[feature_cols],
            train_df[TARGET_COL],
            verbose=args.xgb_verbose,
        )

    print("Training finished.")
    print("-" * 100)
    return model


def summarize_group(df: pd.DataFrame, name: str) -> dict:
    if len(df) == 0:
        return {
            "group": name,
            "count": 0,
            "avg_real_ret_pct": 0.0,
            "median_real_ret_pct": 0.0,
            "win_rate_pct": 0.0,
            "best_ret_pct": 0.0,
            "worst_ret_pct": 0.0,
            "avg_pred_ret_pct": 0.0,
        }

    y = pd.to_numeric(df[TARGET_COL], errors="coerce")
    pred = pd.to_numeric(df["ml_pred_ret_t2_close"], errors="coerce")

    return {
        "group": name,
        "count": int(len(df)),
        "avg_real_ret_pct": round(float(y.mean()), 6),
        "median_real_ret_pct": round(float(y.median()), 6),
        "win_rate_pct": round(float((y > 0).mean() * 100), 6),
        "best_ret_pct": round(float(y.max()), 6),
        "worst_ret_pct": round(float(y.min()), 6),
        "avg_pred_ret_pct": round(float(pred.mean()), 6),
    }


def evaluate_top_buckets(df: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict] = []

    if len(df) == 0:
        return pd.DataFrame(rows)

    rows.append(summarize_group(df, "ALL"))

    for ratio in [0.7, 0.5, 0.3, 0.2, 0.1]:
        n = max(int(len(df) * ratio), 1)
        top = df.sort_values("ml_pred_ret_t2_close", ascending=False).head(n).copy()
        rows.append(summarize_group(top, f"TOP_{int(ratio * 100)}pct"))

    return pd.DataFrame(rows)


def calc_metrics(df: pd.DataFrame) -> dict:
    valid = df[[TARGET_COL, "ml_pred_ret_t2_close"]].dropna()
    if len(valid) == 0:
        return {"rows": 0, "rmse": np.nan, "mae": np.nan, "r2": np.nan, "corr": np.nan}

    y = valid[TARGET_COL]
    p = valid["ml_pred_ret_t2_close"]

    rmse = float(np.sqrt(mean_squared_error(y, p)))
    mae = float(mean_absolute_error(y, p))
    r2 = float(r2_score(y, p))
    corr = float(y.corr(p))

    return {
        "rows": int(len(valid)),
        "rmse": round(rmse, 6),
        "mae": round(mae, 6),
        "r2": round(r2, 6),
        "corr": round(corr, 6),
    }


def predict_splits(
    model: XGBRegressor,
    splits: dict[str, pd.DataFrame],
    feature_cols: list[str],
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    print("=" * 100)
    print("Predicting and evaluating")
    print("=" * 100)

    pred_parts: list[pd.DataFrame] = []
    bucket_parts: list[pd.DataFrame] = []
    metric_rows: list[dict] = []

    items = list(splits.items())
    for split_name, part in progress(items, desc="Predict splits", total=len(items)):
        if len(part) == 0:
            print(f"[WARN] Skip empty split: {split_name}")
            continue

        out = part.copy()
        out["dataset"] = split_name
        out["ml_pred_ret_t2_close"] = model.predict(out[feature_cols])

        metrics = calc_metrics(out)
        metrics["dataset"] = split_name
        metric_rows.append(metrics)

        bucket = evaluate_top_buckets(out)
        bucket.insert(0, "dataset", split_name)
        bucket_parts.append(bucket)

        pred_parts.append(out)

        print("-" * 100)
        print(f"Dataset: {split_name} | rows={len(out):,}")
        print(f"RMSE={metrics['rmse']} | MAE={metrics['mae']} | R2={metrics['r2']} | Corr={metrics['corr']}")
        print(bucket.to_string(index=False))

    pred_df = pd.concat(pred_parts, ignore_index=True) if pred_parts else pd.DataFrame()
    bucket_summary = pd.concat(bucket_parts, ignore_index=True) if bucket_parts else pd.DataFrame()
    metrics_df = pd.DataFrame(metric_rows)

    return pred_df, bucket_summary, metrics_df


def save_outputs(
    model: XGBRegressor,
    pred_df: pd.DataFrame,
    bucket_summary: pd.DataFrame,
    metrics_df: pd.DataFrame,
    feature_cols: list[str],
    output_dir: Path,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    pred_path = output_dir / "xgb_b2_t2_return_predictions.csv"
    bucket_path = output_dir / "xgb_b2_t2_return_bucket_summary.csv"
    metrics_path = output_dir / "xgb_b2_t2_return_metrics.csv"
    feature_path = output_dir / "xgb_b2_t2_return_feature_importance.csv"
    model_path = output_dir / "xgb_b2_t2_return_model.joblib"

    pred_df.to_csv(pred_path, index=False, encoding="utf-8-sig")
    bucket_summary.to_csv(bucket_path, index=False, encoding="utf-8-sig")
    metrics_df.to_csv(metrics_path, index=False, encoding="utf-8-sig")

    feature_importance = pd.DataFrame(
        {
            "feature": feature_cols,
            "importance": model.feature_importances_,
        }
    ).sort_values("importance", ascending=False)

    feature_importance.to_csv(feature_path, index=False, encoding="utf-8-sig")

    joblib.dump(
        {
            "model": model,
            "feature_cols": feature_cols,
            "target_col": TARGET_COL,
        },
        model_path,
    )

    print("=" * 100)
    print("Saved outputs")
    print("=" * 100)
    print(f"Predictions       : {pred_path}")
    print(f"Bucket summary    : {bucket_path}")
    print(f"Metrics           : {metrics_path}")
    print(f"Feature importance: {feature_path}")
    print(f"Model             : {model_path}")
    print("-" * 100)
    print("Feature importance:")
    print(feature_importance.to_string(index=False))
    print("=" * 100)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train XGBoost model for B2 T+2 close return prediction.")

    parser.add_argument("--detail-path", type=Path, default=DEFAULT_DETAIL_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--strategy", default="v0", choices=["v0", "v1", "v2"])

    parser.add_argument("--train-years", default="2022,2023")
    parser.add_argument("--valid-years", default="2024")
    parser.add_argument("--test-years", default="2025")
    parser.add_argument("--observe-years", default="2026")

    parser.add_argument("--n-estimators", type=int, default=300)
    parser.add_argument("--max-depth", type=int, default=3)
    parser.add_argument("--learning-rate", type=float, default=0.03)
    parser.add_argument("--subsample", type=float, default=0.8)
    parser.add_argument("--colsample-bytree", type=float, default=0.8)
    parser.add_argument("--min-child-weight", type=float, default=10.0)
    parser.add_argument("--reg-alpha", type=float, default=0.1)
    parser.add_argument("--reg-lambda", type=float, default=2.0)

    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--n-jobs", type=int, default=-1)
    parser.add_argument("--xgb-verbose", type=int, default=20)

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    raw = read_detail(args.detail_path)
    df, feature_cols = prepare_data(raw, strategy=args.strategy)

    splits = split_by_years(
        df,
        train_years=parse_year_list(args.train_years),
        valid_years=parse_year_list(args.valid_years),
        test_years=parse_year_list(args.test_years),
        observe_years=parse_year_list(args.observe_years),
    )

    model = train_model(
        train_df=splits["train"],
        valid_df=splits["valid"],
        feature_cols=feature_cols,
        args=args,
    )

    pred_df, bucket_summary, metrics_df = predict_splits(
        model=model,
        splits=splits,
        feature_cols=feature_cols,
    )

    if pred_df.empty:
        raise ValueError("No prediction rows generated.")

    save_outputs(
        model=model,
        pred_df=pred_df,
        bucket_summary=bucket_summary,
        metrics_df=metrics_df,
        feature_cols=feature_cols,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)
